services:
  api-server:
    build: ./containers/api-server  # containers/api-serverディレクトリからビルド
    container_name: api-server  # コンテナ名を固定
    volumes:
      - ./containers/api-server:/code  # ローカルの /containers/api-server フォルダをコンテナの /code にマウント
    ports:
      - "8000:8000"
      - "5678:5678"
    working_dir: /code
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    depends_on:
      - databases


  http-server:
    build:
      context: .
      dockerfile: containers/http-server/Dockerfile
    container_name: http-server
    ports:
      - "4200:4200"
    volumes:
      - ./containers/http-server:/code  # index.html がここにある！
    tty: true

  databases:
    image: postgres:15
    container_name: databases
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
