# Generated by Django 5.2 on 2025-05-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("dataset_id", models.AutoField(primary_key=True, serialize=False)),
                ("dataset_name", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
