name: Format Check

on:
  push:
    branches: [develop/1.0.0]
  pull_request:
    branches: [develop/1.0.0]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install formatters
      run: pip install black==24.3.0 isort==6.0.1

    - name: Check isort formatting
      run: isort . --check --diff

    - name: Check black formatting
      run: black . --check