name: Format Check

on:
  push:
    branches: [develop/1.0.0]
  pull_request:
    branches: [develop/1.0.0]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Black and isort
      run: |
        pip install black==24.3.0 isort==5.12.0

    - name: Run isort check
      run: isort . --check-only --diff

    - name: Run black check
      run: black . --check