name: Format Check

on:
  push:
    branches: [develop/1.0.0]
  pull_request:
    branches: [develop/1.0.0]

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # 必要に応じて変更

    - name: isntall black and isort
      run: pip install black isort

    - name: check isort
      run: isort . --check-only --diff

    - name: check black 
      run: black --check .